import {
  computePortfolioSummary,
  enrichHoldings,
  rankCandidates,
} from "@/lib/finance";
import type { BrokerAccount, Holding, Portfolio, Transaction, WorkspaceData } from "@/lib/types";

const portfolio: Portfolio = {
  id: "preview-portfolio",
  name: "Main Portfolio",
  baseCurrency: "RON",
  tags: ["demo", "core"],
};

export const previewBrokerAccounts: BrokerAccount[] = [
  {
    id: "preview-broker-ron",
    portfolioId: portfolio.id,
    name: "XTB RON account",
    broker: "XTB",
    baseCurrency: "RON",
  },
  {
    id: "preview-broker-usd",
    portfolioId: portfolio.id,
    name: "XTB USD account",
    broker: "XTB",
    baseCurrency: "USD",
  },
];

export const previewHoldings: Holding[] = [
  {
    id: "h-aapl",
    portfolioId: portfolio.id,
    symbol: "AAPL",
    companyName: "Apple Inc.",
    quantity: 18,
    averageCost: 165,
    currentPrice: 193,
    currency: "USD",
    marketValue: 3474,
    costBasis: 2970,
    realizedPl: 120,
    unrealizedPl: 504,
    targetAllocation: 18,
    maxAllocation: 24,
    targetBuyPrice: 176,
    targetSellPrice: 224,
    corePercent: 75,
    satellitePercent: 25,
    updatedAt: "2026-06-04T09:00:00.000Z",
  },
  {
    id: "h-msft",
    portfolioId: portfolio.id,
    symbol: "MSFT",
    companyName: "Microsoft Corp.",
    quantity: 9,
    averageCost: 382,
    currentPrice: 445,
    currency: "USD",
    marketValue: 4005,
    costBasis: 3438,
    realizedPl: 0,
    unrealizedPl: 567,
    targetAllocation: 20,
    maxAllocation: 25,
    targetBuyPrice: 410,
    targetSellPrice: 500,
    corePercent: 80,
    satellitePercent: 20,
    updatedAt: "2026-06-04T09:00:00.000Z",
  },
  {
    id: "h-vuaa",
    portfolioId: portfolio.id,
    symbol: "VUAA",
    companyName: "Vanguard S&P 500 UCITS ETF",
    quantity: 25,
    averageCost: 86,
    currentPrice: 96,
    currency: "USD",
    marketValue: 2400,
    costBasis: 2150,
    realizedPl: 0,
    unrealizedPl: 250,
    targetAllocation: 32,
    maxAllocation: 40,
    targetBuyPrice: 92,
    targetSellPrice: null,
    corePercent: 100,
    satellitePercent: 0,
    updatedAt: "2026-06-04T09:00:00.000Z",
  },
  {
    id: "h-nvda",
    portfolioId: portfolio.id,
    symbol: "NVDA",
    companyName: "NVIDIA Corp.",
    quantity: 12,
    averageCost: 92,
    currentPrice: 118,
    currency: "USD",
    marketValue: 1416,
    costBasis: 1104,
    realizedPl: 80,
    unrealizedPl: 312,
    targetAllocation: 8,
    maxAllocation: 12,
    targetBuyPrice: 98,
    targetSellPrice: 132,
    corePercent: 30,
    satellitePercent: 70,
    updatedAt: "2026-06-04T09:00:00.000Z",
  },
];

export const previewTransactions: Transaction[] = [
  {
    id: "t-1",
    portfolioId: portfolio.id,
    brokerAccountId: "preview-broker-ron",
    date: "2026-05-03",
    type: "deposit",
    symbol: null,
    quantity: null,
    price: null,
    amount: 12000,
    currency: "RON",
    source: "manual",
    comment: "Monthly contribution",
  },
  {
    id: "t-2",
    portfolioId: portfolio.id,
    brokerAccountId: "preview-broker-usd",
    date: "2026-05-07",
    type: "buy",
    symbol: "VUAA",
    quantity: 5,
    price: 94,
    amount: 470,
    currency: "USD",
    source: "xtb_import",
    sourceLabel: "XTB import",
    comment: null,
  },
  {
    id: "t-3",
    portfolioId: portfolio.id,
    brokerAccountId: "preview-broker-usd",
    date: "2026-05-11",
    type: "internal_transfer",
    symbol: null,
    quantity: null,
    price: null,
    amount: 2000,
    currency: "USD",
    source: "manual",
    comment: "RON account to USD account",
  },
];

export function getPreviewWorkspaceData(): WorkspaceData {
  const summary = computePortfolioSummary(
    previewHoldings,
    previewTransactions,
    portfolio.baseCurrency
  );
  const holdings = enrichHoldings(previewHoldings, summary.totalValue);

  return {
    isPreview: true,
    isLocked: true,
    userEmail: "preview@investment-ledger.local",
    portfolios: [portfolio],
    activePortfolio: portfolio,
    brokerAccounts: previewBrokerAccounts,
    holdings,
    transactions: previewTransactions,
    summary,
    accumulationCandidates: rankCandidates(holdings, "accumulation"),
    trimmingCandidates: rankCandidates(holdings, "trimming"),
  };
}
